name: backend

services:
  django:
    container_name: backend_django
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    command: /start-django
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "${DJANGO_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    networks:
      - main

  postgres:
    container_name: backend_postgres
    image: postgres:16-bullseye
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    networks:
      - main

volumes:
  postgres_data:

networks:
  main:
