#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python backend/manage.py migrate

script=$(
  cat <<END
from django.contrib.auth import get_user_model

User = get_user_model()
if not User.objects.filter(username="$SUPERUSER_USERNAME").exists():
  User.objects.create_superuser("$SUPERUSER_USERNAME", None, "$SUPERUSER_PASSWORD")

END
)

echo "$script" | python backend/manage.py shell

python backend/manage.py runserver 0.0.0.0:8000
